/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldRouteImport } from './routes/world'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as VerifyDeviceRouteImport } from './routes/verify-device'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SetupCheckRouteImport } from './routes/setup-check'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreenMemoryRouteImport } from './routes/screen-memory'
import { Route as ScreenIntelligenceRouteImport } from './routes/screen-intelligence'
import { Route as ScreenAnalysisRouteImport } from './routes/screen-analysis'
import { Route as ScreenRouteImport } from './routes/screen'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RealityRouteImport } from './routes/reality'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as PhoneIntelligenceRouteImport } from './routes/phone-intelligence'
import { Route as PairDeviceRouteImport } from './routes/pair-device'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ObservatoryRouteImport } from './routes/observatory'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NavigationRouteImport } from './routes/navigation'
import { Route as MobileAgentRouteImport } from './routes/mobile-agent'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LifeRouteImport } from './routes/life'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as KnowledgeConnectRouteImport } from './routes/knowledge-connect'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FutureSelfRouteImport } from './routes/future-self'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as ElementsRouteImport } from './routes/elements'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DeviceConnectRouteImport } from './routes/device-connect'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as CareerRouteImport } from './routes/career'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AppKnowledgeRouteImport } from './routes/app-knowledge'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeSourcesRouteImport } from './routes/knowledge.sources'
import { Route as KnowledgeSearchRouteImport } from './routes/knowledge.search'
import { Route as KnowledgeGraphRouteImport } from './routes/knowledge.graph'
import { Route as KnowledgeChatRouteImport } from './routes/knowledge.chat'
import { Route as DocumentsIdRouteImport } from './routes/documents.$id'
import { Route as AgentsMonitorRouteImport } from './routes/agents.monitor'

const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyDeviceRoute = VerifyDeviceRouteImport.update({
  id: '/verify-device',
  path: '/verify-device',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupCheckRoute = SetupCheckRouteImport.update({
  id: '/setup-check',
  path: '/setup-check',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenMemoryRoute = ScreenMemoryRouteImport.update({
  id: '/screen-memory',
  path: '/screen-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenIntelligenceRoute = ScreenIntelligenceRouteImport.update({
  id: '/screen-intelligence',
  path: '/screen-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenAnalysisRoute = ScreenAnalysisRouteImport.update({
  id: '/screen-analysis',
  path: '/screen-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenRoute = ScreenRouteImport.update({
  id: '/screen',
  path: '/screen',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RealityRoute = RealityRouteImport.update({
  id: '/reality',
  path: '/reality',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneIntelligenceRoute = PhoneIntelligenceRouteImport.update({
  id: '/phone-intelligence',
  path: '/phone-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const PairDeviceRoute = PairDeviceRouteImport.update({
  id: '/pair-device',
  path: '/pair-device',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservatoryRoute = ObservatoryRouteImport.update({
  id: '/observatory',
  path: '/observatory',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationRoute = NavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAgentRoute = MobileAgentRouteImport.update({
  id: '/mobile-agent',
  path: '/mobile-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeRoute = LifeRouteImport.update({
  id: '/life',
  path: '/life',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeConnectRoute = KnowledgeConnectRouteImport.update({
  id: '/knowledge-connect',
  path: '/knowledge-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureSelfRoute = FutureSelfRouteImport.update({
  id: '/future-self',
  path: '/future-self',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementsRoute = ElementsRouteImport.update({
  id: '/elements',
  path: '/elements',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceConnectRoute = DeviceConnectRouteImport.update({
  id: '/device-connect',
  path: '/device-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/app-knowledge',
  path: '/app-knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSourcesRoute = KnowledgeSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeSearchRoute = KnowledgeSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeGraphRoute = KnowledgeGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeChatRoute = KnowledgeChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => KnowledgeRoute,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsMonitorRoute = AgentsMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/app-knowledge': typeof AppKnowledgeRoute
  '/approvals': typeof ApprovalsRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/automations': typeof AutomationsRoute
  '/brain': typeof BrainRoute
  '/career': typeof CareerRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/device-connect': typeof DeviceConnectRoute
  '/devices': typeof DevicesRoute
  '/elements': typeof ElementsRoute
  '/emergency': typeof EmergencyRoute
  '/employee': typeof EmployeeRoute
  '/errors': typeof ErrorsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/future-self': typeof FutureSelfRoute
  '/goals': typeof GoalsRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/knowledge-connect': typeof KnowledgeConnectRoute
  '/learning': typeof LearningRoute
  '/life': typeof LifeRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/mobile-agent': typeof MobileAgentRoute
  '/navigation': typeof NavigationRoute
  '/notifications': typeof NotificationsRoute
  '/observatory': typeof ObservatoryRoute
  '/onboarding': typeof OnboardingRoute
  '/organization': typeof OrganizationRoute
  '/pair-device': typeof PairDeviceRoute
  '/phone-intelligence': typeof PhoneIntelligenceRoute
  '/predictions': typeof PredictionsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/ready': typeof ReadyRoute
  '/reality': typeof RealityRoute
  '/register': typeof RegisterRoute
  '/replay': typeof ReplayRoute
  '/research': typeof ResearchRoute
  '/screen': typeof ScreenRoute
  '/screen-analysis': typeof ScreenAnalysisRoute
  '/screen-intelligence': typeof ScreenIntelligenceRoute
  '/screen-memory': typeof ScreenMemoryRoute
  '/settings': typeof SettingsRoute
  '/setup-check': typeof SetupCheckRoute
  '/system': typeof SystemRoute
  '/timeline': typeof TimelineRoute
  '/trust': typeof TrustRoute
  '/twin': typeof TwinRoute
  '/verification': typeof VerificationRoute
  '/verify-device': typeof VerifyDeviceRoute
  '/workflows': typeof WorkflowsRoute
  '/workspaces': typeof WorkspacesRoute
  '/world': typeof WorldRoute
  '/agents/monitor': typeof AgentsMonitorRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/knowledge/chat': typeof KnowledgeChatRoute
  '/knowledge/graph': typeof KnowledgeGraphRoute
  '/knowledge/search': typeof KnowledgeSearchRoute
  '/knowledge/sources': typeof KnowledgeSourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/app-knowledge': typeof AppKnowledgeRoute
  '/approvals': typeof ApprovalsRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/automations': typeof AutomationsRoute
  '/brain': typeof BrainRoute
  '/career': typeof CareerRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/device-connect': typeof DeviceConnectRoute
  '/devices': typeof DevicesRoute
  '/elements': typeof ElementsRoute
  '/emergency': typeof EmergencyRoute
  '/employee': typeof EmployeeRoute
  '/errors': typeof ErrorsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/future-self': typeof FutureSelfRoute
  '/goals': typeof GoalsRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/knowledge-connect': typeof KnowledgeConnectRoute
  '/learning': typeof LearningRoute
  '/life': typeof LifeRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/mobile-agent': typeof MobileAgentRoute
  '/navigation': typeof NavigationRoute
  '/notifications': typeof NotificationsRoute
  '/observatory': typeof ObservatoryRoute
  '/onboarding': typeof OnboardingRoute
  '/organization': typeof OrganizationRoute
  '/pair-device': typeof PairDeviceRoute
  '/phone-intelligence': typeof PhoneIntelligenceRoute
  '/predictions': typeof PredictionsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/ready': typeof ReadyRoute
  '/reality': typeof RealityRoute
  '/register': typeof RegisterRoute
  '/replay': typeof ReplayRoute
  '/research': typeof ResearchRoute
  '/screen': typeof ScreenRoute
  '/screen-analysis': typeof ScreenAnalysisRoute
  '/screen-intelligence': typeof ScreenIntelligenceRoute
  '/screen-memory': typeof ScreenMemoryRoute
  '/settings': typeof SettingsRoute
  '/setup-check': typeof SetupCheckRoute
  '/system': typeof SystemRoute
  '/timeline': typeof TimelineRoute
  '/trust': typeof TrustRoute
  '/twin': typeof TwinRoute
  '/verification': typeof VerificationRoute
  '/verify-device': typeof VerifyDeviceRoute
  '/workflows': typeof WorkflowsRoute
  '/workspaces': typeof WorkspacesRoute
  '/world': typeof WorldRoute
  '/agents/monitor': typeof AgentsMonitorRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/knowledge/chat': typeof KnowledgeChatRoute
  '/knowledge/graph': typeof KnowledgeGraphRoute
  '/knowledge/search': typeof KnowledgeSearchRoute
  '/knowledge/sources': typeof KnowledgeSourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/app-knowledge': typeof AppKnowledgeRoute
  '/approvals': typeof ApprovalsRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/automations': typeof AutomationsRoute
  '/brain': typeof BrainRoute
  '/career': typeof CareerRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/device-connect': typeof DeviceConnectRoute
  '/devices': typeof DevicesRoute
  '/elements': typeof ElementsRoute
  '/emergency': typeof EmergencyRoute
  '/employee': typeof EmployeeRoute
  '/errors': typeof ErrorsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/future-self': typeof FutureSelfRoute
  '/goals': typeof GoalsRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/knowledge-connect': typeof KnowledgeConnectRoute
  '/learning': typeof LearningRoute
  '/life': typeof LifeRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/mobile-agent': typeof MobileAgentRoute
  '/navigation': typeof NavigationRoute
  '/notifications': typeof NotificationsRoute
  '/observatory': typeof ObservatoryRoute
  '/onboarding': typeof OnboardingRoute
  '/organization': typeof OrganizationRoute
  '/pair-device': typeof PairDeviceRoute
  '/phone-intelligence': typeof PhoneIntelligenceRoute
  '/predictions': typeof PredictionsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/ready': typeof ReadyRoute
  '/reality': typeof RealityRoute
  '/register': typeof RegisterRoute
  '/replay': typeof ReplayRoute
  '/research': typeof ResearchRoute
  '/screen': typeof ScreenRoute
  '/screen-analysis': typeof ScreenAnalysisRoute
  '/screen-intelligence': typeof ScreenIntelligenceRoute
  '/screen-memory': typeof ScreenMemoryRoute
  '/settings': typeof SettingsRoute
  '/setup-check': typeof SetupCheckRoute
  '/system': typeof SystemRoute
  '/timeline': typeof TimelineRoute
  '/trust': typeof TrustRoute
  '/twin': typeof TwinRoute
  '/verification': typeof VerificationRoute
  '/verify-device': typeof VerifyDeviceRoute
  '/workflows': typeof WorkflowsRoute
  '/workspaces': typeof WorkspacesRoute
  '/world': typeof WorldRoute
  '/agents/monitor': typeof AgentsMonitorRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/knowledge/chat': typeof KnowledgeChatRoute
  '/knowledge/graph': typeof KnowledgeGraphRoute
  '/knowledge/search': typeof KnowledgeSearchRoute
  '/knowledge/sources': typeof KnowledgeSourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/app-knowledge'
    | '/approvals'
    | '/assistant'
    | '/audit'
    | '/automations'
    | '/brain'
    | '/career'
    | '/console'
    | '/dashboard'
    | '/device-connect'
    | '/devices'
    | '/elements'
    | '/emergency'
    | '/employee'
    | '/errors'
    | '/events'
    | '/forgot-password'
    | '/future-self'
    | '/goals'
    | '/knowledge'
    | '/knowledge-connect'
    | '/learning'
    | '/life'
    | '/login'
    | '/memory'
    | '/mobile-agent'
    | '/navigation'
    | '/notifications'
    | '/observatory'
    | '/onboarding'
    | '/organization'
    | '/pair-device'
    | '/phone-intelligence'
    | '/predictions'
    | '/profile'
    | '/projects'
    | '/ready'
    | '/reality'
    | '/register'
    | '/replay'
    | '/research'
    | '/screen'
    | '/screen-analysis'
    | '/screen-intelligence'
    | '/screen-memory'
    | '/settings'
    | '/setup-check'
    | '/system'
    | '/timeline'
    | '/trust'
    | '/twin'
    | '/verification'
    | '/verify-device'
    | '/workflows'
    | '/workspaces'
    | '/world'
    | '/agents/monitor'
    | '/documents/$id'
    | '/knowledge/chat'
    | '/knowledge/graph'
    | '/knowledge/search'
    | '/knowledge/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/app-knowledge'
    | '/approvals'
    | '/assistant'
    | '/audit'
    | '/automations'
    | '/brain'
    | '/career'
    | '/console'
    | '/dashboard'
    | '/device-connect'
    | '/devices'
    | '/elements'
    | '/emergency'
    | '/employee'
    | '/errors'
    | '/events'
    | '/forgot-password'
    | '/future-self'
    | '/goals'
    | '/knowledge'
    | '/knowledge-connect'
    | '/learning'
    | '/life'
    | '/login'
    | '/memory'
    | '/mobile-agent'
    | '/navigation'
    | '/notifications'
    | '/observatory'
    | '/onboarding'
    | '/organization'
    | '/pair-device'
    | '/phone-intelligence'
    | '/predictions'
    | '/profile'
    | '/projects'
    | '/ready'
    | '/reality'
    | '/register'
    | '/replay'
    | '/research'
    | '/screen'
    | '/screen-analysis'
    | '/screen-intelligence'
    | '/screen-memory'
    | '/settings'
    | '/setup-check'
    | '/system'
    | '/timeline'
    | '/trust'
    | '/twin'
    | '/verification'
    | '/verify-device'
    | '/workflows'
    | '/workspaces'
    | '/world'
    | '/agents/monitor'
    | '/documents/$id'
    | '/knowledge/chat'
    | '/knowledge/graph'
    | '/knowledge/search'
    | '/knowledge/sources'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/app-knowledge'
    | '/approvals'
    | '/assistant'
    | '/audit'
    | '/automations'
    | '/brain'
    | '/career'
    | '/console'
    | '/dashboard'
    | '/device-connect'
    | '/devices'
    | '/elements'
    | '/emergency'
    | '/employee'
    | '/errors'
    | '/events'
    | '/forgot-password'
    | '/future-self'
    | '/goals'
    | '/knowledge'
    | '/knowledge-connect'
    | '/learning'
    | '/life'
    | '/login'
    | '/memory'
    | '/mobile-agent'
    | '/navigation'
    | '/notifications'
    | '/observatory'
    | '/onboarding'
    | '/organization'
    | '/pair-device'
    | '/phone-intelligence'
    | '/predictions'
    | '/profile'
    | '/projects'
    | '/ready'
    | '/reality'
    | '/register'
    | '/replay'
    | '/research'
    | '/screen'
    | '/screen-analysis'
    | '/screen-intelligence'
    | '/screen-memory'
    | '/settings'
    | '/setup-check'
    | '/system'
    | '/timeline'
    | '/trust'
    | '/twin'
    | '/verification'
    | '/verify-device'
    | '/workflows'
    | '/workspaces'
    | '/world'
    | '/agents/monitor'
    | '/documents/$id'
    | '/knowledge/chat'
    | '/knowledge/graph'
    | '/knowledge/search'
    | '/knowledge/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AssistantRoute: typeof AssistantRoute
  AuditRoute: typeof AuditRoute
  AutomationsRoute: typeof AutomationsRoute
  BrainRoute: typeof BrainRoute
  CareerRoute: typeof CareerRoute
  ConsoleRoute: typeof ConsoleRoute
  DashboardRoute: typeof DashboardRoute
  DeviceConnectRoute: typeof DeviceConnectRoute
  DevicesRoute: typeof DevicesRoute
  ElementsRoute: typeof ElementsRoute
  EmergencyRoute: typeof EmergencyRoute
  EmployeeRoute: typeof EmployeeRoute
  ErrorsRoute: typeof ErrorsRoute
  EventsRoute: typeof EventsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FutureSelfRoute: typeof FutureSelfRoute
  GoalsRoute: typeof GoalsRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  KnowledgeConnectRoute: typeof KnowledgeConnectRoute
  LearningRoute: typeof LearningRoute
  LifeRoute: typeof LifeRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  MobileAgentRoute: typeof MobileAgentRoute
  NavigationRoute: typeof NavigationRoute
  NotificationsRoute: typeof NotificationsRoute
  ObservatoryRoute: typeof ObservatoryRoute
  OnboardingRoute: typeof OnboardingRoute
  OrganizationRoute: typeof OrganizationRoute
  PairDeviceRoute: typeof PairDeviceRoute
  PhoneIntelligenceRoute: typeof PhoneIntelligenceRoute
  PredictionsRoute: typeof PredictionsRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  ReadyRoute: typeof ReadyRoute
  RealityRoute: typeof RealityRoute
  RegisterRoute: typeof RegisterRoute
  ReplayRoute: typeof ReplayRoute
  ResearchRoute: typeof ResearchRoute
  ScreenRoute: typeof ScreenRoute
  ScreenAnalysisRoute: typeof ScreenAnalysisRoute
  ScreenIntelligenceRoute: typeof ScreenIntelligenceRoute
  ScreenMemoryRoute: typeof ScreenMemoryRoute
  SettingsRoute: typeof SettingsRoute
  SetupCheckRoute: typeof SetupCheckRoute
  SystemRoute: typeof SystemRoute
  TimelineRoute: typeof TimelineRoute
  TrustRoute: typeof TrustRoute
  TwinRoute: typeof TwinRoute
  VerificationRoute: typeof VerificationRoute
  VerifyDeviceRoute: typeof VerifyDeviceRoute
  WorkflowsRoute: typeof WorkflowsRoute
  WorkspacesRoute: typeof WorkspacesRoute
  WorldRoute: typeof WorldRoute
  DocumentsIdRoute: typeof DocumentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-device': {
      id: '/verify-device'
      path: '/verify-device'
      fullPath: '/verify-device'
      preLoaderRoute: typeof VerifyDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-check': {
      id: '/setup-check'
      path: '/setup-check'
      fullPath: '/setup-check'
      preLoaderRoute: typeof SetupCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-memory': {
      id: '/screen-memory'
      path: '/screen-memory'
      fullPath: '/screen-memory'
      preLoaderRoute: typeof ScreenMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-intelligence': {
      id: '/screen-intelligence'
      path: '/screen-intelligence'
      fullPath: '/screen-intelligence'
      preLoaderRoute: typeof ScreenIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-analysis': {
      id: '/screen-analysis'
      path: '/screen-analysis'
      fullPath: '/screen-analysis'
      preLoaderRoute: typeof ScreenAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen': {
      id: '/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof ScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reality': {
      id: '/reality'
      path: '/reality'
      fullPath: '/reality'
      preLoaderRoute: typeof RealityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-intelligence': {
      id: '/phone-intelligence'
      path: '/phone-intelligence'
      fullPath: '/phone-intelligence'
      preLoaderRoute: typeof PhoneIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair-device': {
      id: '/pair-device'
      path: '/pair-device'
      fullPath: '/pair-device'
      preLoaderRoute: typeof PairDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observatory': {
      id: '/observatory'
      path: '/observatory'
      fullPath: '/observatory'
      preLoaderRoute: typeof ObservatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-agent': {
      id: '/mobile-agent'
      path: '/mobile-agent'
      fullPath: '/mobile-agent'
      preLoaderRoute: typeof MobileAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life': {
      id: '/life'
      path: '/life'
      fullPath: '/life'
      preLoaderRoute: typeof LifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-connect': {
      id: '/knowledge-connect'
      path: '/knowledge-connect'
      fullPath: '/knowledge-connect'
      preLoaderRoute: typeof KnowledgeConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-self': {
      id: '/future-self'
      path: '/future-self'
      fullPath: '/future-self'
      preLoaderRoute: typeof FutureSelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elements': {
      id: '/elements'
      path: '/elements'
      fullPath: '/elements'
      preLoaderRoute: typeof ElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device-connect': {
      id: '/device-connect'
      path: '/device-connect'
      fullPath: '/device-connect'
      preLoaderRoute: typeof DeviceConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-knowledge': {
      id: '/app-knowledge'
      path: '/app-knowledge'
      fullPath: '/app-knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/sources': {
      id: '/knowledge/sources'
      path: '/sources'
      fullPath: '/knowledge/sources'
      preLoaderRoute: typeof KnowledgeSourcesRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/search': {
      id: '/knowledge/search'
      path: '/search'
      fullPath: '/knowledge/search'
      preLoaderRoute: typeof KnowledgeSearchRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/graph': {
      id: '/knowledge/graph'
      path: '/graph'
      fullPath: '/knowledge/graph'
      preLoaderRoute: typeof KnowledgeGraphRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/chat': {
      id: '/knowledge/chat'
      path: '/chat'
      fullPath: '/knowledge/chat'
      preLoaderRoute: typeof KnowledgeChatRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/monitor': {
      id: '/agents/monitor'
      path: '/monitor'
      fullPath: '/agents/monitor'
      preLoaderRoute: typeof AgentsMonitorRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsMonitorRoute: typeof AgentsMonitorRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsMonitorRoute: AgentsMonitorRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeChatRoute: typeof KnowledgeChatRoute
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  KnowledgeSearchRoute: typeof KnowledgeSearchRoute
  KnowledgeSourcesRoute: typeof KnowledgeSourcesRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeChatRoute: KnowledgeChatRoute,
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  KnowledgeSearchRoute: KnowledgeSearchRoute,
  KnowledgeSourcesRoute: KnowledgeSourcesRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  AppKnowledgeRoute: AppKnowledgeRoute,
  ApprovalsRoute: ApprovalsRoute,
  AssistantRoute: AssistantRoute,
  AuditRoute: AuditRoute,
  AutomationsRoute: AutomationsRoute,
  BrainRoute: BrainRoute,
  CareerRoute: CareerRoute,
  ConsoleRoute: ConsoleRoute,
  DashboardRoute: DashboardRoute,
  DeviceConnectRoute: DeviceConnectRoute,
  DevicesRoute: DevicesRoute,
  ElementsRoute: ElementsRoute,
  EmergencyRoute: EmergencyRoute,
  EmployeeRoute: EmployeeRoute,
  ErrorsRoute: ErrorsRoute,
  EventsRoute: EventsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FutureSelfRoute: FutureSelfRoute,
  GoalsRoute: GoalsRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  KnowledgeConnectRoute: KnowledgeConnectRoute,
  LearningRoute: LearningRoute,
  LifeRoute: LifeRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  MobileAgentRoute: MobileAgentRoute,
  NavigationRoute: NavigationRoute,
  NotificationsRoute: NotificationsRoute,
  ObservatoryRoute: ObservatoryRoute,
  OnboardingRoute: OnboardingRoute,
  OrganizationRoute: OrganizationRoute,
  PairDeviceRoute: PairDeviceRoute,
  PhoneIntelligenceRoute: PhoneIntelligenceRoute,
  PredictionsRoute: PredictionsRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  ReadyRoute: ReadyRoute,
  RealityRoute: RealityRoute,
  RegisterRoute: RegisterRoute,
  ReplayRoute: ReplayRoute,
  ResearchRoute: ResearchRoute,
  ScreenRoute: ScreenRoute,
  ScreenAnalysisRoute: ScreenAnalysisRoute,
  ScreenIntelligenceRoute: ScreenIntelligenceRoute,
  ScreenMemoryRoute: ScreenMemoryRoute,
  SettingsRoute: SettingsRoute,
  SetupCheckRoute: SetupCheckRoute,
  SystemRoute: SystemRoute,
  TimelineRoute: TimelineRoute,
  TrustRoute: TrustRoute,
  TwinRoute: TwinRoute,
  VerificationRoute: VerificationRoute,
  VerifyDeviceRoute: VerifyDeviceRoute,
  WorkflowsRoute: WorkflowsRoute,
  WorkspacesRoute: WorkspacesRoute,
  WorldRoute: WorldRoute,
  DocumentsIdRoute: DocumentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
